### ISSUE TITLE
Executable installer

### ISSUE THREAD

**Issue by arnav56745** [tomlin7/biscuit#125]
I would like to have installer. its more user-friendly.
** create it using a installer program. **
create a **exe** using it

**Comment by billyeatcookies** [comment]
we are using pyinstaller to make the executables currently. 

For making setup files, we can use 
- [innosetup](https://jrsoftware.org/isinfo.php)
- [nsis](https://nsis.sourceforge.io/)

some modifications shall be done to the github workflows

**Comment by tomlin7** [comment]
@arnav56745 This idea won't hold much importance now as biscuit has been added to pypi

installation
```
pip install biscuit-editor
```
running
```
biscuit 
```
