### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by vyshnav-vinod** [tomlin7/biscuit#256]
## Bug
> Describe the bug

Ok so i was trying out the new HTML preview feature and biscuit crashed with this error
`Segmentation fault (core dumped)` . I wanted to know if anyone else also faced this.

So i tried to find what caused this SEGFAULT and found that in a new `html` file if we type,
```html
<html>
<head>
<title>
```
and type the text for the `<title>` it causes this crash. But if we close the `<head>` first and then continue with the `<title>` tag, it wont crash. So something like

```html
<html>
<head>
</head>
``` 
and after closing the head tag, we can then add the `<title>` tag. 

I tried the [faulthandler](https://docs.python.org/3/library/faulthandler.html) module to find some info about the crash and found that it might be caused in the `tkinterweb` package being used. Upon checking their repo i found this [issue](https://github.com/Andereoo/TkinterWeb/issues/47), but this was on MacOS. This might be the problem of the `tkinterweb` package. 
  

### System Information
- OS: Ubuntu 22.04
- Python Version: 3.10.12

**Comment by vyshnav-vinod** [comment]
Also you should probably update `requirements.txt` as it seems `scipy` is now a required package as well?

**Comment by billyeatcookies** [comment]
@vyshnav-vinod scipy was an accidental import 😅 

Most probably we should be able to handle this error and simply give the user some feedback of their code on the GUI. But I'm not sure though, I will experiment and let you know. As you know tkinterweb is backed by tkhtml which is in C, so if this fails then I can't do much to fix the crash.

**Comment by vyshnav-vinod** [comment]
Maybe make a auto complete for the tags?? like when you close the tags like `head` it will automatically add its closing tag `</head>`. This might be a small workaround and i guess `tkhtml` is the one thats causing the crashes

**Comment by tomlin7** [comment]
This is fixed
