### ISSUE TITLE
[Linux] Biscuit crashes on startup due to icon error

### ISSUE THREAD

**Issue by vyshnav-vinod** [tomlin7/biscuit#305]
## Bug

When opening biscuit this error appears :

`_tkinter.TclError: bitmap "/home/.../biscuit/biscuit/res/icon.ico" not defined`

I did some digging and found out that linux does not support [`.ico`](https://stackoverflow.com/a/30271475/23381273). The other filetype suggested was `xbm` but it is black and white. So i tried to open it with PhotoImage and then use a tk.call to set the iconphoto but this is what i got.

![Screenshot from 2024-05-12 12-50-15](https://github.com/tomlin7/biscuit/assets/154617184/5754ca27-08fa-4d50-af09-f6d576dea42d)

I assume this is not the icon you want to be displayed and hence i am not creating the PR.  [This](https://stackoverflow.com/a/60362372/23381273) suggests to use `png` for Linux.
 
But i have created a new branch in my fork and you can checkout the code there. c0d656d

### System Information
- OS: Ubuntu 22.04
- Python Version: 3.10.12

**Comment by tomlin7** [comment]
@vyshnav-vinod Sorry but I can't reproduce this error atm. I saw the fix in your fork, does it resolve the error? then I'd be happy to consider it for a pr! 

Following is the png version of the icon used in windows currently:
![icon](https://github.com/tomlin7/biscuit/assets/70792552/8c2fb54d-cca7-480b-8e71-6afc22af10d6)

**Comment by tomlin7** [comment]
@vyshnav-vinod the condition seems redundant as the following works on windows too
```
icon = ImageTk.PhotoImage(Image.open(self.res.get_res_path("icon.ico")))
self.base.call('wm', 'iconphoto', self.base._w, icon)
```

I can also replace the ico with png in above codeblock, and it would still work pretty fine.

**Comment by vyshnav-vinod** [comment]
@tomlin7 It resolves the error but the icon is not what you would expect. Heres a screenshot
![Screenshot from 2024-05-12 12-50-15](https://github.com/tomlin7/biscuit/assets/154617184/519f06bb-1b96-4f5a-8c41-d1d6724774c8)
Its just white colored.. and not the color of the actual logo

> @vyshnav-vinod the condition seems redundant as the following works on windows too
> 
> ```
> icon = ImageTk.PhotoImage(Image.open(self.res.get_res_path("icon.ico")))
> self.base.call('wm', 'iconphoto', self.base._w, icon)
> ```
> 
> I can also replace the ico with png in above codeblock, and it would still work pretty fine.

And for the conditions.. I just thought you would want two formats for each platform.. so i did the condition and yes it will work fine without it as well/.
