### ISSUE TITLE
Issue & PR viewer 

### ISSUE THREAD

**Issue by tomlin7** [tomlin7/biscuit#313]
## Feature
Currently the github panel lists open issues and prs, but can't see further info on them. Add a new editor type (derive from BaseEditor, see the editor implementations) to view issues and prs.

- we can simply load the website using a simple webview
- or we can fetch data with API and manually render the details

note that we don't plan on managing the issue/pr from editor rn, only presenting the data.

![image](https://github.com/tomlin7/biscuit/assets/70792552/a8ba91b4-8989-4b69-86bc-0dfdb91447e8)

- Github [view implementation](https://github.com/tomlin7/biscuit/tree/main/biscuit/core/components/views/sidebar/github)
- Implementing a new custom editor, 

eg: the [settings editor implementation](https://github.com/tomlin7/biscuit/blob/main/biscuit/core/settings/editor/__init__.py)

https://github.com/tomlin7/biscuit/blob/6fac300455cfbbb3b89d3b22fbb00322948b32c9/biscuit/core/events.py#L172-L173

**Comment by shubhamvrs** [comment]
Assign me this issue!

**Comment by tomlin7** [comment]
@shubhamvrs sure, lemme give you some notes on this

![image](https://github.com/tomlin7/biscuit/assets/70792552/a8ba91b4-8989-4b69-86bc-0dfdb91447e8)

- Github [view implementation](https://github.com/tomlin7/biscuit/tree/main/biscuit/core/components/views/sidebar/github)
- Implementing a new custom editor, 

eg: the [settings editor implementation](https://github.com/tomlin7/biscuit/blob/main/biscuit/core/settings/editor/__init__.py)

https://github.com/tomlin7/biscuit/blob/6fac300455cfbbb3b89d3b22fbb00322948b32c9/biscuit/core/events.py#L172-L173

**Comment by tomlin7** [comment]
@shubhamvrs any updates on this issue?
