### ISSUE TITLE
Built-in editorconfig support

### ISSUE THREAD

**Issue by tomlin7** [tomlin7/biscuit#319]
## Feature
[Editorconfig](https://editorconfig.org/) is quite popular in developer communities and we should incorporate a basic support for this.

- detect editorconfig files in opened project directories
- confirm from user to load the configurations
- use the editorconfig parser and load the configurations

**Comment by Moosems** [comment]
pyeditorconfig module?

**Comment by tomlin7** [comment]
> pyeditorconfig module?

Yeah this will be used.

- run checks for editorconfig detection in project repo on active directory change
- then confirm from user to load the editorconfig settings (using messagebox for now, notification actions are planned)
