### ISSUE TITLE
Recent folders/files: Remove non-existing directories on attempt to open

### ISSUE THREAD

**Issue by tomlin7** [tomlin7/biscuit#375]
## Feature
The recently opened list may contain directories that no longer exist. On attempt to open such directories from recent links, remove them from database.

The recently opened files/folders are shown as a list in [welcome page](https://github.com/tomlin7/biscuit/blob/main/src/biscuit/editor/misc/welcome.py#L99) and through the [palette](https://github.com/tomlin7/biscuit/blob/main/src/biscuit/history.py#L41).
These leverage the [list method here](https://github.com/tomlin7/biscuit/blob/main/src/biscuit/common/fixedstack.py#L22) to generate lambda functions for each recent path.

![image](https://github.com/user-attachments/assets/a32e4345-c27c-4b58-b42e-6613f1c2e16f)

Modify the lambda to call a custom function that will check if the path still exists. If it exists, proceed to open, otherwise, delete the path from db and return.

**Comment by Jawwad011** [comment]
To resolve the issue of opening non-existent directories from the recent list:

1. Retrieve recently opened directories from the database.
2. Check if each directory still exists using os.path.exists().
3. Remove non-existent directories from the database.
4. Commit the changes to keep the list updated.

**Comment by tomlin7** [comment]
@Jawwad011 thanks for the steps, as this is a rough issue outline opened months ago, I didn't document it properly, I'll add more details above.
