### ISSUE TITLE
Saving most recent sessions to local 

### ISSUE THREAD

**Issue by tomlin7** [tomlin7/biscuit#392]
## Feature
Saving most recent session to local storage and then providing an option to restore the session on next startup.
Or even restoring that session automatically (though I think former suits best)

**Comment by RINO-GAELICO** [comment]
Hi @tomlin7 I'd like to tackle this issue, can I have it assigned to me?

**Comment by tomlin7** [comment]
@RINO-GAELICO sure! welcome to the community. Working on this issue will get you a full outline of the project.
You can use an sqlite db to save the sessions (session data may include **opened file paths, opened directory** only for now, however, you can add more suitable)

## Notes
You will get an idea of how to store/restore the session data if you check the history and secrets data store/restore implementations:
- https://github.com/tomlin7/biscuit/blob/main/src/biscuit/views/ai/ai.py#L75
- https://github.com/tomlin7/biscuit/blob/main/src/biscuit/history.py#L22

You can save the data on app close event:
- https://github.com/tomlin7/biscuit/blob/main/src/biscuit/gui.py#L177

You can provide link on the welcome page to restore the session:
- https://github.com/tomlin7/biscuit/blob/main/src/biscuit/editor/misc/welcome.py

**Comment by RINO-GAELICO** [comment]
Thanks a lot for the guidance. 

I opened #422 

Please let me know if I am on the right track. Thanks!
