### ISSUE TITLE
CLI: Implicitly opening passed directory

### ISSUE THREAD

**Issue by tomlin7** [tomlin7/biscuit#402]
## Feature
Following shows the CLI output 
```
Usage: biscuit [OPTIONS] COMMAND [ARGS]...

  Biscuit CLI

Options:
  -v, --version  Show the version and exit.
  -h, --help     Show this message and exit.
  --dev          Run in development mode

Commands:
  clone  Clone & open a git repository in Biscuit
  diff   Diff two files
  doc    Open biscuit documentation
  ext    Commands for managing biscuit extensions
  goto   Open a file and go to a specific location
  open   Open a file or folder in the editor
```

Notice that the `biscuit open [PATH]` command is required to open biscuit in any directory.
Similar to the famous `code .`, biscuit CLI needs to be able to perform `biscuit .` 
i.e. parse the argument passed implicitly as a directory path if it's not a recognized CLI command

Currently this happens
```
$ biscuit .
Usage: biscuit [OPTIONS] COMMAND [ARGS]...

Error: No such command '.'.
```

## Notes
- biscuit uses [python click](https://click.palletsprojects.com/en/8.1.x/)
- [src/biscuit/cli](https://github.com/tomlin7/biscuit/tree/main/src/biscuit/cli)

**Comment by moonlander101** [comment]
Hello, I would like to work on this. To clarify, should it only work for "biscuit ." or should any directory or file be supported?

**Comment by tomlin7** [comment]
Welcome to our small community @moonlander101 Thanks for the comment.

`biscuit .` was only an example for the feature, pardon i didn't mention. This shall work for all kinds of relative and absolute paths:
```
biscuit [path]
```

**Comment by moonlander101** [comment]
Alright thanks, I will try to implement it!
