### ISSUE TITLE
Unable to install from source on Arch Linux

### ISSUE THREAD

**Issue by shirsakm** [tomlin7/biscuit#408]
## Bug
Currently unable to install the program from source with pip, the first command,
```sh
$ pip install tkextrafont scikit-build
```
is unable to install the `tkextrafont` module, as far as I can tell from the [error log](https://github.com/user-attachments/files/17331235/error1.txt).

I believe this is because it requires `scikit-build` to be installed, which is being installed latter, I assumed just installing it first would fix this issue.
```sh
$ pip install scikit-build
$ pip install tkextrafont
```
This still results in an error, and I believe it is an incompatibility between poetry and pip. [Log](https://github.com/user-attachments/files/17331287/error2.txt).

Despite being marked as Windows only, I tried the poetry method. Poetry was installed successfully, and `poetry install` ran without errors. However when trying to run biscuit, I got [import errors](https://github.com/user-attachments/files/17331324/error3.txt).

The only option left is to install the pre-built build and attempt to run it, however this will make it impossible to contribute. I will update this issue with if the build runs or not.

### System Information
- OS: EndeavourOS X86_64
- Kernel: Linux 6.11.2-arch1-1
- Python Version: 3.12.6

**Comment by shirsakm** [comment]
The build did not run. [Errors](https://github.com/user-attachments/files/17331511/error4.txt).

The module installed properly, but also threw errors. [Errors](https://github.com/user-attachments/files/17331528/error5.txt).

**Comment by shirsakm** [comment]
I needed to install the Arch package, `tk` using,
```sh
$ sudo pacman -S tk
```

This fixed the Tkinter issue, but now I get a [new error](https://github.com/user-attachments/files/17331590/error6.txt).

**Comment by tomlin7** [comment]
@shirsakm sorry for the trouble faced. `tkextrafont` lacks good support for some linux distros.
Similar issues regarding this are still open #108 #164 (also #86 related). 

I look forward to https://github.com/TkinterEP/python-tkextrafont/pull/12 which is passing for linux as well. 
@rdbende can you please have a look at these error messages

**Comment by tomlin7** [comment]
@shirsakm make sure you have installed all the prerequisites mentioned in the tkextrafont docs
```
 sudo apt install python3-dev tcl-dev tk-dev \
   fontconfig libfontconfig1 libfontconfig1-dev \
   cmake cmake-data extra-cmake-modules build-essential
 python -m pip install scikit-build
```

**Comment by shirsakm** [comment]
Hi, this worked, however I would like to make a PR to the docs to add documentation for Arch Linux based systems.
Also, I needed to run an extra command after `poetry install`.

```
$ pip install tkextrafont
```
Not sure why, but I suppose that should be added to the docs.

**Comment by tomlin7** [comment]
@shirsakm There were errors when tkextrafont was added to poetry dependencies section for linux, hence its [windows only here](https://github.com/tomlin7/biscuit/blob/main/pyproject.toml#L20). Can you try to reproduce that error in arch by removing the windows only condition from pyproject.toml?

If this is still failing, then yeah definitely this should be in docs, https://github.com/tomlin7/biscuit/blob/main/docs/getting-started/installation.md
