### ISSUE TITLE
Migrate to toml for extensions record (`extensions.json`)

### ISSUE THREAD

**Issue by tomlin7** [tomlin7/biscuit#438]
## Feature
[`extensions.json`](https://github.com/tomlin7/biscuit-extensions/blob/main/extensions.json) will be converted to `extensions.toml`, as a result biscuit extension manager module will have breaking changes.

### Notes
- [ExtensionManager](https://github.com/tomlin7/biscuit/blob/main/src/biscuit/extensions/extensions.py) class

**Comment by shirsakm** [comment]
As the project already uses `.toml` files, what is the standard way of interfacing with them being used?

**Comment by tomlin7** [comment]
@shirsakm Python standard toml library is used to handle the toml files simply. In its current state, the project doesn't use toml anywhere else (config files are not fully done yet).

Switching to toml was a recent decision. There are many essential issues to be worked on, and I do realize that. I will add more details into the issues related to this as soon as possible :)

**Comment by shirsakm** [comment]
In this case the use of TOML files feel pretty redundant. Is there a particular reason you wish to migrate the extensions records from JSON to TOML? TOML is usually used for configurations, while the data here is probably never going to be touched by the end user. I would suggest just sticking with JSON in this case, unless necessary. A more worthwhile change in my opinion would be using `orjson` which will significantly speed up the usage compared to the standard `json` library.

**Comment by shirsakm** [comment]
If you really wish to switch to TOML the only advantage I see is not having two files for recommended and all the extensions, instead being able to store them in one.

```toml
[recommended]
python = [...]
autopep8 = [...]
```

**Comment by tomlin7** [comment]
Well @shirsakm you are right but we will be storing the recommended to a separate list for better accessibility. It's just the clean and minimal syntax being advantage of toml. So the current `extensions.json` needs to be converted to toml as well.
